language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
  # need to update libxml to 2.7.8 to be able to run tests using the
  # LIBXML_HTML_NODEFDTD and LIBXML_HTML_NOIMPLIED libxml constant
  - sudo apt-get update
  - sudo apt-get -o DPkg::Options::="--force-confold" -y upgrade

before_script:
  - composer self-update
  - composer install --dev

script:
  - ./vendor/bin/phpunit -c ./tests
  - ./vendor/bin/phpcs --standard=PSR2 --ignore=tests/Bootstrap.php library tests

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false
